name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Build CMake project
        run: cmake . && cmake --build .
      
      - name: Run unit tests
        run: ./test_unit
      
      - name: Run integration tests
        if: false # TODO: figure out why this step is not working
        run: ./test_integration

      - name: Run ete tests
        run: ./test_ete

      - name: Upload code coverage report
        run: bash <(curl -s https://codecov.io/bash)
